TestSocial/Models/PersonView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using TestSocial.Api.Models;

namespace TestSocial.Models
{
    public class PersonView
    {
        public PersonView()
        {

        }

        public PersonView(Person person)
        {
            Id = person.Id;
            Name = person.Name;
            Surname = person.Surname;
            Patronymic = person.Patronymic;
            DateAge = person.DateAge;
            Address = person.Address;

            CreateStringDate();
        }

        private void CreateStringDate()
        {
            if (DateAge > DateTime.MinValue)
            {
                DateAgeString = DateAge.ToString("d");
            }
        }

        [Key]
        public int Id { get; set; }

        [Required]
        [MaxLength(40)]
        [Display(Name = "Имя")]
        public string Name { get; set; }

        [Required]
        [MaxLength(40)]
        [Display(Name = "Фамилия")]
        public string Surname { get; set; }

        [Required]
        [MaxLength(40)]
        [Display(Name = "Отчество")]
        public string Patronymic { get; set; }
        
        [Display(Name = "Дата рождения")]
        public DateTime DateAge { get; set; }

        [Required]
        [Display(Name = "Дата рождения")]
        public string DateAgeString { get; set; } = string.Empty;

        [MaxLength(300)]
        [Display(Name = "Адрес")]
        public string Address { get; set; }

        public string ErrorMessage { get; set; }

        public Person CreatePerson()
        {
            var person = new Person
            {
                Id = Id,
                Name = Name,
                Surname = Surname,
                Patronymic = Patronymic,
                Address = Address,
                DateAge = DateAge
            };

            if (!string.IsNullOrEmpty(DateAgeString))
            {
                DateTime dateAge;
                if (DateTime.TryParse(DateAgeString, out dateAge))
                {
                    person.DateAge = dateAge;
                }
            }

            return person;
        }
    }
}

TestSocial/Controllers/HomeController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using TestSocial.Api.Controls;
using TestSocial.Api.Infrastructure;
using TestSocial.Api.Models;
using TestSocial.Models;

namespace TestSocial.Controllers
{
    public class HomeController : Controller
    {
        private const string ErrorMessage = "Ошибка во время сохранения";

        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public string Persons(PersonView view)
        {
            var person = view.CreatePerson();

            return GetPersonsJson(person);
        }
        
        public ActionResult Details(int id)
        {
            ViewBag.IdRecord = id;

            return View();
        }

        [HttpGet]
        public ActionResult AddDetails()
        {
            var view = new PersonView();

            return PartialView(view);
        }

        [HttpGet]
        public ActionResult EditDetails(int id)
        {
            PersonView view = null;
            using (var control = new PersonControl())
            {
                var person = control.Get(id);
                if (person != null)
                    view = new PersonView(person);
            }

            return PartialView(view);
        }

        [HttpPost]
        public ActionResult AddDetails( PersonView view)
        {
            if (!ModelState.IsValid)
                return PartialView(view);

            bool isSave = Save(ref view, 0);
            if (!isSave)
            {
                TempData["ErrorMessage"] = ErrorMessage;
            }

            return RedirectToAction("Details", new { id = view.Id });
        }

        [HttpPost]
        public ActionResult EditDetails(int id, PersonView view)
        {
            if (!ModelState.IsValid)
                return PartialView(view);
            
            bool isSave = Save(ref view, id);
            if (!isSave)
            {
                view.ErrorMessage = ErrorMessage;
            }

            return PartialView(view);
        }

        public JsonResult DeleteDetails(int id)
        {
            string errorMessage = string.Empty;
            bool isDelete = false;
            try
            {
                using (var control = new PersonControl())
                {
                    isDelete = control.Delete(id);
                }
            }
            catch (SocialException ex)
            {
                errorMessage = ex.Message;
            }
            catch (Exception ex)
            {
                errorMessage = "Ошибка во время удаления записи";
            }

            return Json(new { IsDelete = isDelete, Error = errorMessage }, JsonRequestBehavior.AllowGet);
        }

        private List<PersonView> CreatePersonView(List<Person> persons)
        {
            var views = new List<PersonView>();
            foreach (var person in persons)
            {
                var view = new PersonView(person);
                views.Add(view);
            }

            return views;
        }

        private string GetPersonsJson(Person person)
        {
            var persons = new List<Person>();
            using (var control = new PersonControl())
            {
                var exp = (Expression<Func<Person, bool>>)person.GetExpression();
                persons = control.GetAll(exp);
            }

            var views = CreatePersonView(persons);
            return JsonConvert.SerializeObject(views);
        }

        private bool Save(ref PersonView view, int id)
        {
            view.Id = id;
            var person = view.CreatePerson();
            bool isSave = false;
            bool isEdit = id > 0;
            try
            {
                using (var control = new PersonControl())
                {
                    isSave = control.Save(person, isEdit);
                    view.Id = person.Id;
                }
            }
            catch (Exception ex)
            {
                
            }

            return isSave;
        }
    }
}

TestSocial/Controllers/RelativesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestSocial.Api.Controls;
using TestSocial.Api.Infrastructure;
using TestSocial.Api.Models;
using TestSocial.Models;

namespace TestSocial.Controllers
{
    public class RelativesController : Controller
    {
        // GET: Relatives
        public ActionResult Show(int personId)
        {
            var views = new List<PersonView>();
            var persons = new List<Person>();
            using (var control = new RelativesControl())
            {
                persons = control.GetPersons(personId);
            }

            foreach (var person in persons)
            {
                var view = new PersonView(person);
                views.Add(view);
            }

            ViewBag.PersonId = personId;

            return PartialView(views);
        }

        public ActionResult Delete(int personId, int relativeId)
        {
            bool isDelete = false;
            string errorMessage = string.Empty;
            try
            {
                using (var control = new RelativesControl())
                {
                    isDelete = control.Delete(personId, relativeId);
                }
            }
            catch (SocialException ex)
            {
                errorMessage = ex.Message;
            }
            catch (Exception ex)
            {
                errorMessage = "Ошибка во время удаления записи";
            }

            return Json(new { IsDelete = isDelete, ErrorMessage = errorMessage }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AddRelative(int personId, int relativeId)
        {
            bool isAdd = false;
            string errorMessage = string.Empty;
            try
            {
                using (var control = new RelativesControl())
                {
                    isAdd = control.AddRelative(personId, relativeId);
                }
            }
            catch (SocialException ex)
            {
                errorMessage = ex.Message;
            }
            catch (Exception ex)
            {
                errorMessage = "Ошибка во время добавления связи";
            }

            return Json(new { IsAdd = isAdd, ErrorMessage = errorMessage }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GridMaster(int personId)
        {
            return PartialView(personId);
        }
    }
}

TestSocial/Views/Home/AddDetails.cshtml
@using TestSocial.Models
@model PersonView

@{ 
    string errorMessage = TempData["ErrorMessage"] as string;
}

<div id="DetailsForm" class="main-center">
    @using (Html.BeginForm("AddDetails", "Home", FormMethod.Post,
        new { id = "RegistrationForm", @class = "form-horizontal" }))
    {
        if (!string.IsNullOrEmpty(errorMessage))
        {
            <span class="field-validation-valid text-danger">@errorMessage</span>
        }

        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "control-label cols-sm-2" })
            <div class="cols-sm-10">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control required-field" })
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Surname, new { @class = "control-label cols-sm-2" })
            <div class="cols-sm-10">
                @Html.TextBoxFor(m => m.Surname, new { @class = "form-control required-field" })
                @Html.ValidationMessageFor(m => m.Surname, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Patronymic, new { @class = "control-label cols-sm-2" })
            <div class="cols-sm-10">
                @Html.TextBoxFor(m => m.Patronymic, new { @class = "form-control required-field" })
                @Html.ValidationMessageFor(m => m.Patronymic, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.DateAgeString, new { @class = "control-label cols-sm-2" })
            <div class="cols-sm-10">
                @Html.TextBoxFor(m => m.DateAgeString, new { @class = "form-control required-field" })
                @Html.ValidationMessageFor(m => m.DateAgeString, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Address, new { @class = "control-label cols-sm-2" })
            <div class="cols-sm-10">
                @Html.TextAreaFor(m => m.Address, new { @class = "form-control required-field" })
                @Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div style="float: right;">
                <input type="submit" id="SubmitRegistration" class="btn btn-default" value="Сохранить">
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    $("#DateAgeString").datepicker({
        dateFormat: 'dd.mm.yy'
    });
</script>

TestSocial/Views/Home/DeleteDetailsDialog.cshtml
<div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <h4>Вы точно хотите удалить запись?</h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" onclick="GridControl.deleteRecord(); $('#DeleteModal').modal('hide');">Да</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Нет</button>
            </div>
        </div>
    </div>
</div>

TestSocial/Views/Home/Details.cshtml
@{ 
    int idRecord = 0;
    if (ViewBag.IdRecord != null)
    {
        idRecord = (int)ViewBag.IdRecord;
    }
}

<div class="form-details">
    <h4 class="header-text" style="margin: 10px 0px;">Пользователь</h4>
    <div class="block-details" style="padding: 10px 30px;">
        @if (idRecord == 0)
        {
            @Html.Action("AddDetails", "Home")
        }
        else
        {
            @Html.Action("EditDetails", "Home", new { id = idRecord })
        }
    </div>
</div>

@if (idRecord > 0)
{
    <div class="social-details">
        <h4 class="header-text" style="margin: 10px 0px;">Родственники</h4>
        <div class="block-details" style="padding: 5px 8px;">
            <button type="button" class="btn btn-link btn-add-social" data-target="#PanelGridMaster" data-toggle="modal">
                <span class="glyphicon glyphicon-plus"></span>
                Добавить
            </button>
            <div id="BlockSocial">
                @Html.Action("Show", "Relatives", new { personId = idRecord })
            </div>
        </div>
    </div>

    @Html.Partial("~/Views/Relatives/PanelGridMaster.cshtml", idRecord)
}

<a href="javascript:void(0)" class="exit-details header-text" onclick="AppControl.loadHomePage()">Выйти</a>

TestSocial/Views/Home/EditDetails.cshtml
@using TestSocial.Models
@model PersonView

<div id="DetailsForm">
    @using (Ajax.BeginForm("EditDetails", "Home", new { id = Model.Id },
        new AjaxOptions
        {
            HttpMethod = "POST",
            UpdateTargetId = "DetailsForm",
            InsertionMode = InsertionMode.Replace
        },
        new { id = "RegistrationForm", @class = "form-horizontal" }))
    {
        if (!string.IsNullOrEmpty(Model.ErrorMessage))
        {
            <span class="field-validation-valid text-danger">@Model.ErrorMessage</span>
        }

        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "control-label cols-sm-2" })
            <div class="cols-sm-10">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control required-field" })
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Surname, new { @class = "control-label cols-sm-2" })
            <div class="cols-sm-10">
                @Html.TextBoxFor(m => m.Surname, new { @class = "form-control required-field" })
                @Html.ValidationMessageFor(m => m.Surname, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Patronymic, new { @class = "control-label cols-sm-2" })
            <div class="cols-sm-10">
                @Html.TextBoxFor(m => m.Patronymic, new { @class = "form-control required-field" })
                @Html.ValidationMessageFor(m => m.Patronymic, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.DateAgeString, new { @class = "control-label cols-sm-2" })
            <div class="cols-sm-10">
                @Html.TextBoxFor(m => m.DateAgeString, new { @class = "form-control required-field" })
                @Html.ValidationMessageFor(m => m.DateAgeString, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Address, new { @class = "control-label cols-sm-2" })
            <div class="cols-sm-10">
                @Html.TextAreaFor(m => m.Address, new { @class = "form-control required-field" })
                @Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div style="float: right;">
                <input type="submit" id="SubmitRegistration" class="btn btn-default" value="Сохранить">
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    $("#DateAgeString").datepicker({
        dateFormat: 'dd.mm.yy'
    });
</script>

TestSocial/Views/Home/Index.cshtml
<div id="gridPanel">
    <button type="button" class="btn btn-default" onclick="GridControl.addRecord()">Добавить</button>
    <button type="button" class="btn btn-default" onclick="GridControl.editRecord()">Изменить</button>
    <button type="button" class="btn btn-danger" id="DeleteDetails" data-target="#DeleteModal">Удалить</button>
</div>
<div id="gridSocial"></div>

<script type="text/javascript">
    $(function () {
        var selectedRow;
        $("#gridSocial").jsGrid({
            height: "100%",
            width: "100%",
            editinig: false,
            filtering: true,
            autoload: true,

            pageSize: 15,
            pageButtonCount: 5,

            loadMessage: "Загрузка данных...",

            controller: {
                loadData: function (filter) {
                    var deferred = $.Deferred();
                    return $.ajax({
                        type: "GET",
                        url: "/Home/Persons",
                        data: filter,
                        dataType: "json",
                        success: function (data) {
                            deferred.resolve(data);
                        }
                    });
                },
            },
            
            rowClick: function (args) {
                if (selectedRow != null) {
                    selectedRow.children('.jsgrid-cell').css('background-color', '');
                }
                var $row = this.rowByItem(args.item);
                $row.children('.jsgrid-cell').css('background-color', '#c4e2ff');
                selectedRow = $row;
                GridControl.selectedRow = args.item;
            },

            rowDoubleClick: function(args) {
                GridControl.editRecord();
            },

            fields: [
                { name: "Id", width: 50 },
                { name: "Name", title: "Имя", type: "text", width: 100 },
                { name: "Surname", title: "Фамилия", type: "text", width: 100 },
                { name: "Patronymic", title: "Отчество", width: 100 },
                { name: "DateAge", title: "Дата рождения", type: "date", myCustomProperty: "bar", width: 100 },
                { name: "Address", title: "Адрес", width: 100 },
                { type: "control", editButton: false, deleteButton: false, clearFilterButton: true, }
            ]
        });
    });

    $("#DeleteDetails").click(function () {
        if (GridControl.selectedRow != null) {
            $("#DeleteModal").modal();
        }
    });
</script>

<script src="~/Scripts/Project/GridControl.js"></script>
@Html.Partial("~/Views/Home/DeleteDetailsDialog.cshtml")

TestSocial/Views/Relatives/GridMaster.cshtml
@model int

<div id="gridSocial"></div>

<script type="text/javascript">
    $(function () {
        var selectedRow;
        $("#gridSocial").jsGrid({
            height: "100%",
            width: "100%",
            editinig: false,
            filtering: true,
            autoload: true,

            pageSize: 15,
            pageButtonCount: 5,

            loadMessage: "Загрузка данных...",

            controller: {
                loadData: function (filter) {
                    var deferred = $.Deferred();
                    return $.ajax({
                        type: "GET",
                        url: "/Home/Persons",
                        data: filter,
                        dataType: "json",
                        success: function (data) {
                            deferred.resolve(data);
                        }
                    });
                },
            },

            rowClick: function (args) {
                if (selectedRow != null) {
                    selectedRow.children('.jsgrid-cell').css('background-color', '');
                }
                var $row = this.rowByItem(args.item);
                $row.children('.jsgrid-cell').css('background-color', '#c4e2ff');
                selectedRow = $row;
                GridControl.selectedRow = args.item;
            },

            rowDoubleClick: function(args) {
                GridControl.addRelative(@(Model));
            },

            fields: [
                { name: "Id", width: 50 },
                { name: "Name", title: "Имя", type: "text", width: 100 },
                { name: "Surname", title: "Фамилия", type: "text", width: 100 },
                { name: "Patronymic", title: "Отчество", width: 100 },
                { name: "DateAge", title: "Дата рождения", type: "date", myCustomProperty: "bar", width: 100 },
                { type: "control", editButton: false, deleteButton: false, clearFilterButton: true, }
            ]
        });
    });
</script>

TestSocial/Views/Relatives/PanelGridMaster.cshtml
@model int

<div class="modal fade" id="PanelGridMaster" tabindex="-1" role="dialog" aria-labelledby="MasterLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn btn-danger" onclick="GridControl.addRelative(@(Model));">Добавить</button>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="float: right; margin-top: 0px;">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/Project/GridControl.js"></script>
<script type="text/javascript">
    $("#PanelGridMaster").on("show.bs.modal", function (e) {
        $(this).find(".modal-body").load("@("/Relatives/GridMaster?personId=" + Model)");
    });
</script>

TestSocial/Views/Relatives/Show.cshtml
@using TestSocial.Models
@model List<PersonView>

@{ 
    int personId = (int)ViewBag.PersonId;
}

<div class="list-group list-social">
    @foreach (var view in Model)
    {
        <div class="list-group-item group-list-social">
            <div class="left-group-social">
                <a href=@("/Home/Details?Id=" + view.Id)>
                    <h4 class="list-group-item-heading">
                        @string.Format("{0} {1} {2}", view.Surname, view.Name, view.Patronymic)
                    </h4>
                </a>
                <p class="list-group-item-text"><b>Дата рождения: </b>@view.DateAgeString</p>
                <p class="list-group-item-text"><b>Адрес: </b>@view.Address</p>
            </div>
            <a href="javascript:void(0)" onclick="SocialControl.deleteRecord(@(personId), @(view.Id))" class="right-group-social">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </div>
    }
</div>

<script src="~/Scripts/Project/SocialControl.js"></script>

TestSocial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Scripts/jsgrid/jsgrid.css" rel="stylesheet" />
    <link href="~/Scripts/jsgrid/jsgrid-theme.min.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jsgrid/jsgrid.min.js"></script>
    <script src="~/Scripts/Project/JsGridExtension.js"></script>
    <script src="~/Scripts/Project/AppControl.js"></script>
</head>
<body class="social-background">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Test social", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>
</body>
</html>